services:
  app:
    container_name: radikorec
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
      # 必要に応じて他の環境変数をここに追加するか、env_file を使用してください
    volumes:
      - ./records:/app/records
      - ./radikorec.db:/app/radikorec.db
      - ./.env:/app/.env
