services:
  app:
    container_name: radikorec
    build: .
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    volumes:
      - ./public/records:/app/public/records:z
      - ./data:/app/data:z
      - ./.env:/app/.env:z
